name: Continuous Integration - Testing
  
on:
  pull_request:
    branches: [ "main" ]

jobs:
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: |
          npm run test-coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Test Coverage
          summary-title: LH-Backend Coverage Report
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false

      - name: Jest Output file
        continue-on-error: true
        run: npm run test-output
        
      - name: Process jest results with default
        if: always()
        # You may also reference just the major or major.minor version
        uses: im-open/process-jest-test-results@v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'jest-results.json'
