name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: YARN install
        run: yarn install --frozen-lockfile
      - name: Install Pods
        run: |
          cd ./ios/
          pod install
      - uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: Unity-iPhone.xcworkspace # optional
