name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Working Directory
        run: |
          cd ./ios/
      - name: Deploy
        uses: vfrascello/xcode-deploy@v1.5
        with:
          xcode-version: '13.2'
          configuration: 'Release'
          scheme: 'eventapp'
          path-to-export-options: 'exportOptions.plist'
          update-build: true
          install-pods: false
          resolve-package-dependencies: true
          distribution-certificate-p12: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
          distribution-certificate-password: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
          app-store-provisioning-profile: ${{ secrets.APPSTORE_PROVISIONING_PROFILE}}
          auth-key-id: ${{ secrets.AUTH_KEY_ID }}
          auth-key-issuer-id: ${{ secrets.AUTH_KEY_ISSUER_ID }}
          auth-key-p8: ${{ secrets.AUTH_KEY_P8 }}
